In [58]:
import feedparser
import pandas as pd
import numpy as np
import re
from datetime import datetime
import spacy

In [59]:
#Solo ejecutar la primera vez
corpus = pd.DataFrame(columns = ['Source','Title','Content','Section','URL','Date'])
corpus.head()

Empty DataFrame
Columns: [Source, Title, Content, Section, URL, Date]
Index: []

#### RSS de la Jornada

In [60]:
deportes_jornada = feedparser.parse('https://www.jornada.com.mx/rss/deportes.xml?v=1')
economia_jornada = feedparser.parse('https://www.jornada.com.mx/rss/economia.xml?v=1')
cultura_jornada = feedparser.parse('https://www.jornada.com.mx/rss/cultura.xml?v=1')
ciencia_jornada = feedparser.parse('https://www.jornada.com.mx/rss/ciencias.xml?v=1')

#### RSS de Expansión

In [61]:
tecnologia_expansion = feedparser.parse('https://expansion.mx/rss/tecnologia')
economia_expansion = feedparser.parse('https://expansion.mx/rss/economia')

In [62]:
def jornada (jornada_parser):
    # Crear una lista para almacenar los datos
    data_list = []

    for entry in jornada_parser.entries:

        # Extraer la sección a partir del enlace
        link = entry.title_detail.base
        match = re.search(r'/rss/(\w+)\.xml', link)
        entry_link = match.group(1) if match else 'Unknown'

        # Convertir la fecha de publicación al formato 01/01/2000
        fecha = deportes_jornada.entries[0].published
        fecha_obj = datetime.strptime(fecha, '%a, %d %b %Y %H:%M:%S GMT')
        fecha_format = fecha_obj.strftime('%d/%m/%Y')

                # Crear un diccionario con los datos
        row_data = {
            'Source': 'Jornada',
            'Title': entry.title,
            'Content': entry.summary,
            'Section': entry_link,
            'URL': entry.links[0].href,
            'Date': fecha_format
        }
        # Checamos que no exista esa noticia en el corpus
        if entry.title not in corpus['Title']:
            # Añadir el diccionario a la lista
            data_list.append(row_data)
        
    # Convertir la lista de diccionarios en un DataFrame
    df = pd.DataFrame(data_list, columns=['Source', 'Title', 'Content', 'Section', 'URL', 'Date'])
    
    return df

In [63]:
def expansion(Expansion_Parser):
    # Crear una lista para almacenar los datos
    data_list = []

    for entry in Expansion_Parser.entries:

        # Extraer la sección a partir del enlace
        link = entry.title_detail.base 
        match = re.search(r'rss\/(\w+)', link)
        entry_link = match.group(1) if match else 'Unknown'

        # Convertir la fecha de publicación al formato 01/01/2000
        fecha = entry.published
        fecha_obj = datetime.strptime(fecha, '%a, %d %b %Y %H:%M:%S GMT')
        fecha_format = fecha_obj.strftime('%d/%m/%Y')

        # Crear un diccionario con los datos
        row_data = {
            'Source': 'Expansion',
            'Title': entry.title,
            'Content': entry.summary,
            'Section': entry_link,
            'URL': entry.link,
            'Date': fecha_format
        }
        
        # Checamos que no exista esa noticia en el corpus
        if entry.title not in corpus['Title']:
            # Añadir el diccionario a la lista
            data_list.append(row_data)
    
    # Convertir la lista de diccionarios en un DataFrame
    df = pd.DataFrame(data_list, columns=['Source', 'Title', 'Content', 'Section', 'URL', 'Date'])
    
    return df

In [64]:
tecnologia_exp_df = expansion(tecnologia_expansion)
tecnologia_exp_df.head()

,Source,Title,Content,Section,URL,Date
0,Expansion,China avanza en su regulación para identificar...,En el país asiático están buscando implementar...,tecnologia,https://expansion.mx/tecnologia/2024/09/27/nue...,27/09/2024
1,Expansion,"En medio de la crisis, la industria del gaming...",Los despidos han marcado el año de los videoju...,tecnologia,https://expansion.mx/tecnologia/2024/09/27/cri...,27/09/2024
2,Expansion,Oracle construirá un centro hyperscale en Nuev...,"Samuel García, gobernador del estado, resaltó ...",tecnologia,https://expansion.mx/tecnologia/2024/09/26/ora...,26/09/2024
3,Expansion,OpenAI planea reestructuración para ser una em...,Este cambio representaría una oportunidad para...,tecnologia,https://expansion.mx/tecnologia/2024/09/26/ope...,26/09/2024
4,Expansion,Meta empareja a OpenAI y Google en la carrera ...,"Durante el evento Meta Connect, Mark Zuckerber...",tecnologia,https://expansion.mx/tecnologia/2024/09/26/met...,26/09/2024

In [65]:
economia_exp_df = expansion(economia_expansion)
economia_exp_df.head()

,Source,Title,Content,Section,URL,Date
0,Expansion,El gasto de consumidores en EU aumenta en agos...,El gasto de los consumidores sigue apoyándose ...,economia,https://expansion.mx/economia/2024/09/27/gasto...,27/09/2024
1,Expansion,"México registra déficit comercial de 4,868 mdd...",Las exportaciones mexicanos cayeron 1% y las i...,economia,https://expansion.mx/economia/2024/09/27/balan...,27/09/2024
2,Expansion,Banxico mantendrá prudencia y cerrará el año c...,Los analistas consideran que el mensaje del ba...,economia,https://expansion.mx/economia/2024/09/27/banxi...,27/09/2024
3,Expansion,Banxico ejecuta nuevo recorte a la tasa a 10.5%,El banco central hizo un segundo recorte conse...,economia,https://expansion.mx/economia/2024/09/26/banxi...,26/09/2024
4,Expansion,Janet Yellen se opone a reducir requisitos de ...,La secretaria del Tesoro de Estados Unidos pid...,economia,https://expansion.mx/economia/2024/09/26/yelle...,26/09/2024

In [66]:
ciencia_jor_df = jornada(ciencia_jornada)
ciencia_jor_df.head()

Empty DataFrame
Columns: [Source, Title, Content, Section, URL, Date]
Index: []

In [67]:
cultura_jor_df = jornada(cultura_jornada)
cultura_jor_df.head()

Empty DataFrame
Columns: [Source, Title, Content, Section, URL, Date]
Index: []

In [68]:
economia_jor_df = jornada(economia_jornada)
economia_jor_df.head()

Empty DataFrame
Columns: [Source, Title, Content, Section, URL, Date]
Index: []

In [69]:
deportes_jor_df = jornada(deportes_jornada)
deportes_jor_df.head()

Empty DataFrame
Columns: [Source, Title, Content, Section, URL, Date]
Index: []

In [70]:
corpus = pd.concat([tecnologia_exp_df,economia_exp_df, deportes_jor_df, economia_jor_df, ciencia_jor_df, cultura_jor_df], axis = 0)
corpus

,Source,Title,Content,Section,URL,Date
0,Expansion,China avanza en su regulación para identificar...,En el país asiático están buscando implementar...,tecnologia,https://expansion.mx/tecnologia/2024/09/27/nue...,27/09/2024
1,Expansion,"En medio de la crisis, la industria del gaming...",Los despidos han marcado el año de los videoju...,tecnologia,https://expansion.mx/tecnologia/2024/09/27/cri...,27/09/2024
2,Expansion,Oracle construirá un centro hyperscale en Nuev...,"Samuel García, gobernador del estado, resaltó ...",tecnologia,https://expansion.mx/tecnologia/2024/09/26/ora...,26/09/2024
3,Expansion,OpenAI planea reestructuración para ser una em...,Este cambio representaría una oportunidad para...,tecnologia,https://expansion.mx/tecnologia/2024/09/26/ope...,26/09/2024
4,Expansion,Meta empareja a OpenAI y Google en la carrera ...,"Durante el evento Meta Connect, Mark Zuckerber...",tecnologia,https://expansion.mx/tecnologia/2024/09/26/met...,26/09/2024
...,...,...,...,...,...,...
45,Expansion,Claudia Sheinbaum se reunirá con empresarios d...,En medio de voces empresariales que dicen que ...,economia,https://expansion.mx/economia/2024/09/18/ebrar...,18/09/2024
46,Expansion,¿Dónde hay mayor brecha salarial por género en...,Banxico realizó un análisis de las brechas sal...,economia,https://expansion.mx/economia/2024/09/18/brech...,18/09/2024
47,Expansion,¿Por qué es importante tener un seguro para tu...,"Un seguro no solo cubre los daños materiales, ...",economia,https://expansion.mx/economia/2024/09/18/por-q...,18/09/2024
48,Expansion,Peligra economía de México si Trump gana y cum...,La agencia calificadora anticipa que la econom...,economia,https://expansion.mx/economia/2024/09/18/econo...,18/09/2024
49,Expansion,"RappiCard alcanza los 5,107 millones de pesos ...",La empresa resalta que parte de su estrategia ...,economia,https://expansion.mx/economia/2024/09/18/rappi...,18/09/2024

In [71]:
corpus = corpus.reset_index(drop=True)
corpus.to_csv('corpuses/raw/corpus1.csv')